### ISSUE TITLE
Provide a stable sorting implementation

### ISSUE THREAD

**Issue by z5h** [elm-community/list-extra#11]
Elm's `List.sortWith` is implemented via `Arrays.prototype.sort` which is not guaranteed to be stable.

I'd like a stable sort for lists.

I have an implementation working based on porting the following Scheme code to Elm: http://www.scheme.com/tspl3/examples.html#./examples:h2.

Happy to make a pull request if this makes sense.

``` Elm
doSort : (m -> m -> Basics.Order) -> List m -> Int -> List m
doSort pred list n =
  if n == 1 then 
    List.take 1 list
  else
    let 
      i = n // 2
    in
      doMerge pred (doSort pred list i) (doSort pred (List.drop i list) (n - i))

doMerge : (m -> m -> Basics.Order) -> List m -> List m -> List m
doMerge pred l1 l2 =
  let 
    h1 = List.head l1
    h2 = List.head l2
  in
    case (h1, h2) of
      (Nothing, _) ->
        l2
      (_, Nothing) ->
        l1
      (Just h1', Just h2') ->
        if pred h2' h1' == Basics.LT then
          h2' :: (doMerge pred l1 (List.drop 1 l2))
        else
          h1' :: (doMerge pred (List.drop 1 l1) l2)

stableSortWith : (m -> m -> Basics.Order) -> List m -> List m
stableSortWith pred list =
  if List.isEmpty list then
    list
  else
    doSort pred list (List.length list)
```

**Comment by mgold** [comment]
Yes, this seems PR-worthy. A few quick notes:
- Please use `a` instead of `m` for type variables.
- Let's do some renaming to avoid one-letter-one-number names, especially for lower L! And also primes. And use pattern matching directly instead of List module functions. (please double check this is still correct)

``` elm
doMerge pred listX listY =
    case (listX, listY) of
      ([], _) ->
        listY
      (_, []) ->
        listX
      (x::xs, y::ys) ->
        if pred x y == LT then
          y :: (doMerge pred listX ys)
        else
          x :: (doMerge pred xs listY)
```

**Comment by z5h** [comment]
@mgold thanks for the quick reply.
I may have been a bit hasty. This is not properly tail-recursive and will exceed call stack size if the list to sort is beg enough. I see issues like this are ongoing in core https://github.com/elm-lang/core/pull/668

So is that acceptable, or should we be looking to rework this code before a PR?

**Comment by mgold** [comment]
Take your time and get it right. The library will still be here.

**Comment by z5h** [comment]
I've modified my above code with some changes and using Trampoline. It is brutally slow.

I've reimplemented using an idea found online.
The idea is to force any sort to be stable by comparing on the original values and defer to comparing their indices if that original comparison was `EQ`.

This way we can piggyback on `List.sortWith` and get much better performance. Code follows. Will open a PR once this idea is double-checked.

``` Elm
stableSortWith : (a -> a -> Basics.Order) -> List a -> List a
stableSortWith pred list =
  let
    listWithIndex = List.indexedMap (\i a -> (a, i)) list
    predWithIndex (a1, i1) (a2, i2) = 
      let 
        result = pred a1 a2
      in
        case result of
          Basics.EQ ->
            Basics.compare i1 i2
          _ ->
            result
  in
    List.sortWith predWithIndex listWithIndex |> List.map fst
```
