### ISSUE TITLE
`group` example in docs returns wrong type

### ISSUE THREAD

**Issue by Janiczek** [elm-community/list-extra#111]
`group` returns `List (a, List a)` but the example doesn't reflect that:

```elm
group  [1,2,2,3,3,3,2,2,1] == [[1],[2,2],[3,3,3],[2,2],[1]]
```

**Comment by Chadtech** [comment]
Thanks! I didnt notice this. Yeah in `8.0.0` the group functions changed pretty fundamentally. I'll fix this soon.

**Comment by pzp1997** [comment]
I think we should start using [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples) so that this will not happen in the future. See issue #50.

**Comment by Chadtech** [comment]
Sounds good to me. Ilias recommended that too. Lets do it.

**Comment by Chadtech** [comment]
We are using elm-verify-examples now, and this particular issue was resolved.
