### ISSUE TITLE
Suggestion: Deprecate filterNot

### ISSUE THREAD

**Issue by jehoshua02** [elm-community/list-extra#12]
I think we want to avoid bloat and rely on simple primitives where we can no?

filterNot can be as simple as using function composition with things implemented in core

```
List.filter (not << myFunction) myList
```

The potential danger in keeping something like this around is that users will then expect Not functions for every other data structure. I think it's good that users discover the power of function composition and application and to point them toward core library whenever possible.

Update: I'm open to hearing reasons for keeping it though.

**Comment by mgold** [comment]
I think people understand that, by including it in a filter library, it won't be included in core libraries. My other objection is that removing it isn't worth a major release, but your proposal is to merely deprecate it. So, I could go either way.

(For my money, Ruby picked the right names `select` and `reject` for these functions, but `filter` comes most directly from Haskell.)

**Comment by jehoshua02** [comment]
@mgold I like `select` and `reject` better than `filter` and `filterNot`. Feels more natural and clean.

**Comment by jehoshua02** [comment]
Honestly, after sleeping on it, I feel like having function inverses could be a good thing because they could be intuitive and natural to learn. While we could always `not << ...`, that is slightly awkward, especially for newcomers. It was a whole week before I learned that `not << ...` was what I needed for a particular case.

**Comment by EverybodyKurts** [comment]
@jehoshua02 Regardless of whether or not this function is kept, I wish your tip was in Elm's api documentation for `filter`. It's a handy little tip.
