### ISSUE TITLE
MIT LICENSE file does not match "BSD-3-Clause" in elm.json

### ISSUE THREAD

**Issue by rlefevre** [elm-community/list-extra#125]
`LICENSE`:
https://github.com/elm-community/list-extra/blob/7f468f61e8f65696bf21f676ad81e50e865c4fa6/LICENSE#L1

`elm.json`:
https://github.com/elm-community/list-extra/blob/7f468f61e8f65696bf21f676ad81e50e865c4fa6/elm.json#L5

**Comment by Chadtech** [comment]
Thank you. WIth the Elm 0.19 upgrade the BSD-3 license must have slipped in. I changed it to "MIT" to be consistent with the pre-existing license.
