### ISSUE TITLE
isInfixOf returns incorrect result when a partial match is found before a complete match

### ISSUE THREAD

**Issue by mthiems** [elm-community/list-extra#132]
In version 8.2.2
Small example, shown in repl:

```
> List.Extra.isInfixOf [1,2] [1,3,1,2]
False : Bool
```

It should return `True` .

The problem is that the implementation switches to `isPrefixOf` as soon as a single item matches.

**Comment by pzp1997** [comment]
Good catch! I just opened a PR with a fix.

**Comment by Chadtech** [comment]
Thank you @mthiems for reporting. And thank you @pzp1997 for fixing.
