### ISSUE TITLE
foldl/foldr rename

### ISSUE THREAD

**Issue by OvermindDL1** [elm-community/list-extra#14]
The `foldl` and `foldr` implementations in this package conflict with the default so both cannot be brought in at once.  However the main thing is that many languages have both a `foldl`/`foldr`, which iterate while taking the default accumulator, but also have a `reducel`/`reducer`, which are `foldl`/`foldr` but they take the first element as the accumulator initial state if two elements, else return the first or empty list, basically what the List.Extra.`foldl`/`foldr` are doing now.  Thus renaming them to be `reducel`/`reducer` would allow being able to import both List and List.Extra simultaneously for such functions.  This would be a major version number change, but well worth it to get done early.

**Comment by jvoigtlaender** [comment]
> The foldl and foldr implementations in this package conflict with the default so both cannot be brought in at once.

What are you talking about? This package does not export `foldl` and `foldr` functions. It exports `foldl1` and `foldr1` functions, which do not conflict with anything in `core`.

**Comment by OvermindDL1** [comment]
Er, missed the '1', that honestly makes it even more confusing to me though.  :-)

I've always experienced in functional languages that `fold` folds a list of things into an accumulator, where `reduce` reduces a list of things to a single of that same thing, which is what `foldl1`/`foldr1` are doing.

**Comment by jvoigtlaender** [comment]
Then you seem to not have encountered that not so uncommon functional language `Haskell`. :smile:

Where the `foldl1` and `foldr1` names come from.

**Comment by OvermindDL1** [comment]
Haskell has a _lot_ of poorly named things due to how its standard library grew, others were better designed initially.  ^.^

In essence, the '1' makes no sense, what does it mean?  Does it mean the foldl/foldr work only on 1 value?  Return only 1 value (in which case how would it be different from the stock foldl/foldr)?  There is no correspondance from '1' to its operation, unlike reduce, which does.  ;-)

**Comment by jvoigtlaender** [comment]
I'm not the maintainer of this package. But let's just keep for the record that neither of these two arguments apply:
- There is a conflict with `core`. - No, there is not.
- The names are different from what one always finds in functional languages. - No, that's not true. See Haskell, and possibly other functional languages inspired by Haskell.

As to your question what the `1` means: For me, it means that the function works on lists of length at least one.

**Comment by OvermindDL1** [comment]
The main argument I was putting for was proper descriptive naming however.  Reduce is used by quite a number of languages and is descriptive as to its functionality unlike the current names.

**Comment by jvoigtlaender** [comment]
Can you give an example of a functional language (link to their standard library) where 
- `fold` is used for what `List.foldr` is and
- `reduce` is used for what `List.Extra.foldr1` is? 

I haven't seen a language that uses both `fold` and `reduce` as names, but that may not mean much, since I don't know all functional languages.

**Comment by OvermindDL1** [comment]
Ah, I use them quite often, here are the ones that I can bring up off the top of my head:
- F# (`reduce` == `List.Extra.foldl1`, `fold` == `List.foldl`):
  - Core:  https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/list.reduce%5B't%5D-function-%5Bfsharp%5D
  - (As much as I am not a fan of Microsoft products, F# really is like a Haskell done better... although not as pure)
- CL (`reduce` == `List.Extra.foldl1`, `reduce_from` == `List.foldl`):
  - Core:  http://clhs.lisp.se/Body/f_reduce.htm
  - Popular Emacs variant: https://github.com/magnars/dash.el
- Elixir (`reduce` == `List.Extra.foldl1`, `foldl` == `List.foldl`):
  - Core:  http://elixir-lang.org/docs/stable/elixir/Enum.html#reduce/2
  - Core:  http://elixir-lang.org/docs/stable/elixir/List.html#foldl/3
- Clojure (`reduce` == `List.Extra.foldl1`, `fold` == `List.foldl`):
  - Core:  https://clojuredocs.org/clojure.core/reduce
  - Core:  https://clojuredocs.org/clojure.core.reducers/reduce
  - Core:  https://clojuredocs.org/clojure.core.reducers/fold

And I know there are many others, just not off the top of my mind.  The **only** languages I can come up with off the top of my mind (no doubt there are others) that use the `1` variants are Haskell, and nothing else, even in Elm `reduce` is in a non-core library (via the `1` variants at https://github.com/elm-community/list-extra).  ^.^

**Comment by jvoigtlaender** [comment]
Okay, so can you open a new issue please, with that information and none of our distracting discussion above about arguments that do not actually apply?

**Comment by jvoigtlaender** [comment]
The descriptions of the situations for both Elixir and Clojure above are wrong. For example, in Elixir the difference between `fold`ing and `reduc`ing is not about "providing an initial accumulator or not". Instead, it is about "working on lists or working on enumerables". Proof:
- Look at their types.
- Consider that there is a http://elixir-lang.org/docs/stable/elixir/Enumerable.html#reduce/3.

The situation for Clojure is similar. I haven't looked at F# and CL yet. But we should have accurate information if we are to make decisions about Elm's functions based on situations in other languages.

**Comment by OvermindDL1** [comment]
In Elixir the reason foldl is over lists is because it is brought over from the original Erlang definition where reduce was added to Elixir but was not in Erlang (erlang had nothing like reduce, had to use `:lists.foldl(fun, hd(mylist), tl(mylist))` to get a reduce).  However as reduce was newer they wanted it to be more generically useful if anything implemented an enumerable type (which did not exist in Erlang, the only enumerable was a list), however that is because enumerable's are convertable to a list so if someone wants to foldl over an enumerable then they can do so (such as with maps, which become a list of 2-tuples).

Clojure is not similar but is different in another unique regard, both work transparently over `Collection` types however it uses `reduce` for both `foldl` and `reducel` functionality.  However its own `foldl` is a parallel `reduce` of the `foldl` variety.  Clojure is one of those languages that does not have arbitrary curry but rather has functions of defined arities so it can use reduce for both styles (and in fact many languages that do have arity as part of the function name, like Clojure, do use `reduce` for both `reduce` and `fold` style functionality, depending on whether an initial accumulator was supplied or not).

**Comment by jvoigtlaender** [comment]
Well, just concentrating on the Elixir case:
- The reasoning you describe there about the different types and why this means that both `fold` and `reduce` exist does not exactly sound like that standard library went through a better desing process than Haskell's. :smile:
- You haven't addressed the point that Elixir has both a `reduce/2` that is like `foldl1` and a `reduce/3` that is like `foldl`. These two being present completely void the claim that Elixir uses `reduce` for Elm's `List.Extra` thing and `fold` for Elm's `List` thing. In fact, you could take the Elixir example as motivation to require that `core` should rename `fold` to `reduce`, because after all Elixir has `reduce/3` which does the same thing (just on general collections).

I really don't get how from this one can construe an argument for "`List.fold` should remain named `fold` and `List.Extra.fold1` should be renamed `reduce`". It's just not backed at all by looking to Elixir.

**Comment by OvermindDL1** [comment]
Elixir does not have native function currying, as I have found recently it seems that languages that where the arity is part of the function name (like elixir and clojure and some others) use reduce with 2 or 3 arguments for both reduce/fold functionality respectively, and languages that have native currying (like F# and such) tend to use reduce/fold for as such functionality.  As elm is a native currying language, it makes sense for reduce/fold.  ^.^

**Comment by jvoigtlaender** [comment]
Yes, a more accurate picture is forming now.

**Comment by OvermindDL1** [comment]
That is only some though, take Scala or scheme, which are also function/arity languages, they instead use reduce/fold.  The reduce/fold pattern definitely seems to be the most common by far.  I'm finding a lot of uses of them through-out languages (including a couple of languages I've not heard of, need to learn these...).  There is a lot of history I am learning as well.  For example Elixir basically copied Clojure's Enumeration style (as stated by the author), and Haskell's very odd naming convention was apparently back from before it got higher kinded types (which Elm sorely needs) and it had to specialize functions more based on their types so they kept them simple and namespaced without using generic names so they could be used in the future if it needed to be (which apparently they never did).  It is quite a fascinating history read among all these languages.

Interestingly, smalltalk calls these 'inject', which is entirely different and I've not found a historical reasoning for it yet...
