### ISSUE TITLE
`chunksOf` function

### ISSUE THREAD

**Issue by nixypanda** [elm-community/list-extra#20]
Would you be open to add a `chunksOf` function which is defined like this.
```elm
{-|
   Given a list make chunks of length n from it
   NOTE: last one can be less than n
 -}
chunksOf : Int -> List a -> List (List a)
chunksOf n xs =
  case xs of
    [] ->
      []

    _ ->
      let
        (ys, zs) = splitAt n xs
      in
        ys :: chunksOf n zs
```
I searched for a similar function but was unable to find one

**Comment by jvoigtlaender** [comment]
> I searched for a similar function but was unable to find one

Maybe you didn't use the appropriate search strategy. That strategy is: 
- Go to http://package.elm-lang.org/
- Click the "Fancy Search" link
- Enter the type of your desired function into the search box
- Be happy that your desired function apparently does already exist.

**Comment by nixypanda** [comment]
Oops my bad

**Comment by jvoigtlaender** [comment]
Oh, nothing bad about it.

In fact, that you were looking for that functionality here may raise the question whether it is useful to have `list-extra` and `list-split` as separate packages.
