### ISSUE TITLE
Function to group by some property, and return tuples of the property and the sub-list

### ISSUE THREAD

**Issue by wmakley** [elm-community/list-extra#21]
Thanks for this library, I use it all the time! I forked it and am trying to add a function "groupBy" to transform a List where each element has some shared comparable property like this:

```elm
list : List (Int, String)
list =
    [ (1, "a"), (1, "b"), (2, "c") ]

{-| Output:
    [ (1, [ (1, "a"), (1, "b") ] )
    , (2, [ (2, "c") ] )
    ]
-}
grouped : List (Int, List (Int, String))
grouped =
    List.Extra.groupBy fst list
```

I am having trouble because I am still pretty slow at functional programming and it feels like solving an incredibly arduous math problem, so I figured I'd at least make an issue in case someone else with more experience can do it easily.

**Comment by jvoigtlaender** [comment]
Seems you want http://package.elm-lang.org/packages/elm-community/dict-extra/1.3.1/Dict-Extra#groupBy. If you really want a list in the end, you can just follow up that function with a call to Dict.toList.

**Comment by wmakley** [comment]
Perfect, thanks!
