### ISSUE TITLE
Add cross

### ISSUE THREAD

**Issue by mgold** [elm-community/list-extra#3]
It would be helpful to have this function:

``` elm
cross : List a -> List b -> List (a,b)

cross [1,2,3] ["a", "b"] = [(1, "a"), (1, "b"), (2, "a"), (2, "b"), (2, "a"), (2, "b")]
```

The use case I have in mind is getting a list of grid intersections, e.g. `cross [0..m] [0..m]`.

**Comment by jvoigtlaender** [comment]
That's just `lift2 (,)` with the function `lift2` already in this package. Is it really worth an extra function?

**Comment by mgold** [comment]
Nope, although a documentation comment might be nice :)
