### ISSUE TITLE
updateAt/setAt/swapAt could return a List (not a Maybe List)

### ISSUE THREAD

**Issue by cbenz** [elm-community/list-extra#32]
Several functions like [`removeAt : Int -> List a -> List a`](https://github.com/elm-community/list-extra/blob/c6f1616ae1a8bdb226638944464f9a7088c6b3f7/src/List/Extra.elm#L591) or [`updateIfIndex : (Int -> Bool) -> (a -> a) -> List a -> List a`](https://github.com/elm-community/list-extra/blob/c6f1616ae1a8bdb226638944464f9a7088c6b3f7/src/List/Extra.elm#L478) return a `List a` and that's fine (from my point of view)!

On the other hand,  [`updateAt : Int -> (a -> a) -> List a -> Maybe (List a)`](https://github.com/elm-community/list-extra/blob/c6f1616ae1a8bdb226638944464f9a7088c6b3f7/src/List/Extra.elm#L468) returns a `Maybe (List a)` which is annoying.

May we change this to `updateAt : Int -> (a -> a) -> List a -> List a`?

The same remark applies to `setAt` and `swapAt`.

These functions could return the original list when the index is invalid.

What do you think about it? Shall I send a pull-request in that direction?

---

Use case:

```elm
numbers = [14, 42, 99]

numbers |> updateIfIndex ((==) 0) (\n -> n + 1)
-- should be the same than
numbers |> updateAt 0 (\n -> n + 1)

-- but with current we have to do:
numbers |> updateAt 0 (\n -> n + 1) |> Maybe.withDefault numbers
```

**Comment by mgold** [comment]
Seems reasonable to me. Was there any reason why you'd want to know if the index supplied was invalid?

**Comment by cbenz** [comment]
No particular reason for me.

So I'm going to start a PR.
