### ISSUE TITLE
new feat.: groupBy : (a -> String) -> List a -> Dict String (List a)

### ISSUE THREAD

**Issue by witoldsz** [elm-community/list-extra#38]
Grouping lists by a key.
I can implement it if you are short on time, just need a green light.

**Comment by jvoigtlaender** [comment]
It's always a good idea to first search whether the function already exists elsewhere. Specifically, http://klaftertief.github.io/elm-search/ lets you search by type. Entering your intended function type there, gives: http://package.elm-lang.org/packages/elm-community/dict-extra/1.3.2/Dict-Extra#groupBy

So your feature request here is superfluous.
