### ISSUE TITLE
Proposal for `prepend`

### ISSUE THREAD

**Issue by EverybodyKurts** [elm-community/list-extra#44]
Here's an example (super easy way) of doing it:

```elm
prepend : List a -> List a -> List a
prepend prependee prepended =
    List.concat [ prepended, prependee ]
```

If can create a merge request with the appropriate docs and tests if approved.

**Comment by mgold** [comment]
You can already do `prepended ++ prependee`. This seems like a reverse of that, and doesn't seem worthwhile to me.

**Comment by EverybodyKurts** [comment]
Ha, I learned something new.

I'm fine with this decision. It's just weird to me that there's a `List.append` in the core library but no `List.prepend`. I also like to think that the two method names, `append` and `prepend`, are bit more intention revealing.

Anywho, just my two thoughts.

**Comment by mgold** [comment]
If you're fine with it, I'll close the issue.
