### ISSUE TITLE
Release planning

### ISSUE THREAD

**Issue by Chadtech** [elm-community/list-extra#76]
I bet Elm 0.19 is just around the corner. Since we have a lot of major updates lets wait until 0.19 to publish the next version of list-extra. Does that sound good? After Elm 0.19 comes out we can do a kind of last call on major updates, and do some of the house cleaning tasks like cohering variable names.

Does that sound good?

**Comment by silky** [comment]
is elm 0.19 still coming?

i was keen to have this package today, on elm 0.18, but it's not available

**Comment by Chadtech** [comment]
I just published a major update. 0.19 seems further off than I expected, but more importantly I couldnt justify to myself withholding these changes. I think I was trying to be cautious, but in reality it just meant holding back useful updates.

**Comment by Chadtech** [comment]
After publishing, I've seen two folks come into the Elm slack with dependency problems due to the recent major update. I dont know how representative those two cases are, but that could mean that major updates on `List-Extra` are quite disruptive. So moving forward I think we should do major updates no more than once a year. 

Any other ideas on how to minimize dependency problems for people?

**Comment by michaeljones** [comment]
I'm grateful for the release. I agree that major releases shouldn't be done any more than considered necessary but where necessary semver is meant to inform users of potential problems. It could be that the Elm ecosystem is generally stable enough that they were surprised that a package update might require changes but it shouldn't be surprising as it is a major version number bump. 

I think artificially restricting releases of important fixes is a potentially problematic tactic. I think that breaking API changes for the sake of being cleaner or more consistent could be limited to less frequent releases and possibly done in conjunction with major Elm releases. Though if 0.19 has taught anything it is that you have no way to know when an Elm release might come so attempting to plan around it is sort of futile.

**Comment by pzp1997** [comment]
I think we can close this now that the package has been updated for 0.19.
